from constants import *

## each measure has 8 duration

MEASURE_1 = [
    ("E5", NOTE_DURATION), ("E5", NOTE_DURATION), ("REST", NOTE_DURATION), ("E5", NOTE_DURATION), ("REST", NOTE_DURATION),
    ("C5", NOTE_DURATION), ("E5", NOTE_DURATION * 2),
]

MEASURE_2 = [
    ("G5", 2 * NOTE_DURATION), ("REST", 2 * NOTE_DURATION),
    ("G4", NOTE_DURATION * 2), ("REST", NOTE_DURATION * 2),
]

MEASURE_3 = [
    ("C5", NOTE_DURATION * 2), ("REST", NOTE_DURATION), ("G4", NOTE_DURATION * 2), ("REST", NOTE_DURATION), ("E4", NOTE_DURATION * 2),
]

MEASURE_4 = [
    ("REST", NOTE_DURATION), ("A4", NOTE_DURATION), ("B4", NOTE_DURATION * 2), ("A#4", NOTE_DURATION), ("A4", NOTE_DURATION),
]

MEASURE_5 = [
    ("G4", NOTE_DURATION * 0.66), ("E5", NOTE_DURATION * 0.66), ("G5", NOTE_DURATION  * 0.66), ("A5", NOTE_DURATION * 2), ("F5", NOTE_DURATION), ("G5", NOTE_DURATION),
]

MEASURE_6 = [
    ("REST", NOTE_DURATION),("E5", NOTE_DURATION * 2), ("C5", NOTE_DURATION), ("D5", NOTE_DURATION), ("B4", NOTE_DURATION), ("REST", NOTE_DURATION),
]

MEASURE_7 = [
    ("REST", NOTE_DURATION * 2), ("G5", NOTE_DURATION), ("F#5", NOTE_DURATION), ("F5", NOTE_DURATION), ("D#5", NOTE_DURATION * 2), ("E5", NOTE_DURATION)
]

MEASURE_8 = [
    ("REST", NOTE_DURATION), ("G#4", NOTE_DURATION), ("A4", NOTE_DURATION), ("C5", NOTE_DURATION), ("REST", NOTE_DURATION), ("A4", NOTE_DURATION), ("C5", NOTE_DURATION),("D5", NOTE_DURATION),
]

MEASURE_9 = [
    ("REST", NOTE_DURATION), ("C6", NOTE_DURATION * 2), ("C6", NOTE_DURATION), ("C6", NOTE_DURATION * 2), ("REST", NOTE_DURATION * 2),
]

MEASURE_10 = [
    ("REST", NOTE_DURATION * 2), ("D#5", NOTE_DURATION * 2), ("REST", NOTE_DURATION), ("D5", NOTE_DURATION * 2),
]

MEASURE_11 = [
    ("C5", NOTE_DURATION * 2), ("REST", NOTE_DURATION * 6),
]

